services:
  app_backend:
    image: santy0811/flask_app:latest
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - servidor_bd
    ports:
      - "5050:5000"
    networks:
      - red_cba

  servidor_bd:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_cba

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - red_cba

  uptime_kuma:
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - red_cba

  dozzle:
    image: amir20/dozzle:latest
    restart: always
    ports:
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red_cba

  signal_cli_rest_api:
    image: bbernhard/signal-cli-rest-api:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - red_cba

networks:
  red_cba:

volumes:
  mysql_data:
  npm_data:
  letsencrypt:
  uptime_kuma_data:
    